sudo: false
language: scala
scala:
- 2.12.2
script:
- sbt clean test publish
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
env:
  global:
  - secure: SZKuNoH0VG6+2qnS6bDSfc1v1bLUxsMvNkfW+hEt7O84usYdn7XRL/hNy+/UWxIXgDMxffHuIwF0MebDJDZhW7FgdTPtQLVrJMJZfkn96CFSSVXAhwrloQgVqttD0hQMiqqawj7nLt7K05o58QxtToitTE6n5CkveqHwC1jMv6SFRonIbAsrfX7dkFNWHuj/YFwbfBusm8i0w5m7w9Npbj5Vyg42UhPWOCkKaz9v9PHKdKWfTuBCjRMMBG+BM3LaTGGc9rwYdQt5rj0Zuv5tWcHNe1y5pWY/HIfdPn+V9S08Fz4deWQBQXwvB1YxS9BD/bOIB0j/KcWRqFa2sVRvljzdAR67WCMBTdo0laEqxXCUSKaIZh6cP/qBmv9Cf6TpsflJf9Tr3IP/qq0yVUX7Q0e0Q3ClXmvZzJSSMnditjzUpF0ZH57MuaLLJzwRBDGozR4zKBxPbznL/wBDHFe2st0BeDER33By3yEOMIba7LvKhuWA64yDYE6PtUTXv33pny61T9B0JLzpQSc2t867DiiSeWtYOyaTDxkFlD6fKqFQulf4rw/pAyhL/qoq2BWFLRaqvoNiTzJyHa0lf2rRS2a+Jll6xDlkC8MOTKhuw0rtWmEL3R7nB1ftcN5LlJuKKjCNLi3XvCq0MSmxzJFOBZOZ1OUtkwqur0ZuJnEVh5M=
  - secure: pcEfiGFFViffKq+8Kz11CxKPbVao4Fz4An0OEkS1Cm0O/M8TMRSpHODbocHBip8x6W8P8Da2HxIAbZ0oNVAhkQQf8gJGuuQ1Hj2b83divlxflvrx7uXFOIwwAROZbXBMc3V78vTJOD32F4BgH9JFydXbGqh1FjXE/pAN4xXI3iyYV+t8Jg/nwa6fUz+jYlxjmBGod1ttH+uAr2Dcxw+iXmG0vK+lXlER72TU7wy4GLCOVOcka17Q64z/Q9yJT9SQMVfqHXTdMSMgH5sK/m3qQI0m+pwp7l+826eWuUoXT4WaYYRPEp8XsGqpzYMoZscy1fObKt9v4P5Pp/DcYYmSmcPvmePxQuHXFI7R7TgDIypzLwHshd7qbC2j6YjFZsOaYHXrl27vCAG8ROgwpxC1xGIw17FQqIxkBy5Nc5gmX90+NR/apmCApqgrz9UwVGONKDYBy0xk2TwbhfgnPWEutW6rHDAAO/aEylV+kiGiLv0jE7vSNPuRtpflQhqkZeaMXOxqVQ53hCqlnFZggkmUZ9cxPeTJGN7DpPPBmzXD+pQqLDerG2lhpMznhCq6GFbHiwro0zVXq5rQ/C2uPGDfCfhKK2TS89WfPMzau0n5gQTedDfikpB6GXdJreRDuXOeMlif4PMeJg4v9GIDflzpT4IZHAW8lyrbjYbtqnTPP3M=
